name: "Pull Request Continuous Integration"

on: [pull_request]

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Lint with flake8
      run: |
        flake8 phoenix tests
    - name: Test with pytest
      run: |
        pytest -v
    - name: Verify build
      run: |
        pip install --upgrade pip wheel
        python setup.py bdist_wheel
